print("Hello, Pythonista.")
print("Let's see if you remember something from your previous Python lessons.")
print("First, I will ask you: what is your name? ")
myname=input()
print(f"Hello, {myname}.")
namelength=len(myname)
print(f"Oh, your name is {namelength} characters long. That is good luck!")
print("If you don't mind me asking, how old are you? ")
myage=input()
print("Oh, so you will be "+str(int(myage)+1) + " in just under a year.")